version: '3'

services:
  app:
    build: .
    tty: true
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    build:
      context: '.'
      dockerfile: 'db.Dockerfile'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api-auth-example
